-- Backfill recipe image_url values from local source data
BEGIN;

UPDATE recipes AS r
SET image_url = v.image_url
FROM (VALUES
  ('Air Fryer Gochujang Chicken Skewers', 'https://moribyan.com/wp-content/uploads/2025/04/IMG_0289.jpg'),
  ('Almond Raspberry Scones', 'https://moribyan.com/wp-content/uploads/2025/01/IMG_0551.jpg'),
  ('Apple Cider Spice Loaf', 'https://moribyan.com/wp-content/uploads/2025/10/IMG_2074.jpg'),
  ('Arugula Cucumber Feta Salad', '/static/meal-images/a24c6067986d.png'),
  ('Avocado Quinoa Power Salad', 'https://moribyan.com/wp-content/uploads/2024/07/IMG_0144.jpg'),
  ('Baked Ziti with Brown Rice Pasta', 'https://moribyan.com/wp-content/uploads/2022/05/Baked-Ziti-2-scaled-1.jpg'),
  ('Banana Bread Oatmeal Bake', 'https://moribyan.com/wp-content/uploads/2024/01/IMG_9860.jpg'),
  ('Banana Bread Pancakes', 'https://moribyan.com/wp-content/uploads/2025/11/IMG_2029.jpg'),
  ('Banana Cake with Brown Butter Frosting', 'https://moribyan.com/wp-content/uploads/2023/12/IMG_9796-scaled.jpeg'),
  ('Banana French Toast Muffins', 'https://moribyan.com/wp-content/uploads/2026/01/IMG_3646.jpg'),
  ('Bang Bang Chicken Skewers', 'https://moribyan.com/wp-content/uploads/2024/01/IMG_9898.jpg'),
  ('Beef and Broccoli Stir-Fry', 'https://moribyan.com/wp-content/uploads/2025/08/IMG_1097.jpg'),
  ('Beef and Cheese Borek Rolls', 'https://moribyan.com/wp-content/uploads/2022/05/IMG_6726-scaled-1.jpg'),
  ('Beef and Lamb Sausage Rolls', 'https://moribyan.com/wp-content/uploads/2026/02/IMG_0286.jpg'),
  ('Beef and Potato Hash', '/static/meal-images/49e30eed166a.png'),
  ('Beef Chorizo and Chicken Pasta', 'https://moribyan.com/wp-content/uploads/2023/03/IMG_0812-1.jpg'),
  ('Beef Kebab Rice Plate', '/static/meal-images/79478cb9ff9f.png'),
  ('Black Bean and Corn Salad', '/static/meal-images/c1a032541ad6.png'),
  ('Brown Rice', '/static/meal-images/78b25a94a60a.png'),
  ('Butter Chicken', '/static/meal-images/a67f32086faf.png'),
  ('Butter Chicken Bowl', '/static/meal-images/565b6347ed0a.png'),
  ('Butter Chicken Bowl Plus', '/static/meal-images/3faac12b373e.png'),
  ('Butter Chicken Thighs', '/static/meal-images/18b7a59b6b08.png'),
  ('Cassava Flour Beignets', 'https://moribyan.com/wp-content/uploads/2024/04/IMG_0036.jpg'),
  ('Charred Zucchini with Herbs', '/static/meal-images/ef12aabb0097.png'),
  ('Chicken Sausage Kale Scramble', '/static/meal-images/b408a7a0fcda.png'),
  ('Chicken Shawarma Bowl', '/static/meal-images/62f0c6bccf41.png'),
  ('Chicken Shawarma Plate', '/static/meal-images/5231f22403b6.png'),
  ('Chickpea Mac N'' Beef', '/static/meal-images/c81e71c1a374.png'),
  ('Chocolate Chip Cookies', '/static/meal-images/d726139d3bc0.png'),
  ('Cilantro Lime Cabbage Slaw', '/static/meal-images/a4a7bd27c04f.png'),
  ('Classic Apple Hand Pies', 'https://moribyan.com/wp-content/uploads/2022/11/IMG_9968.jpg'),
  ('Cottage Cheese Power Bowl with Turkey Bacon', '/static/meal-images/3c89a4d09aed.png'),
  ('Creamy Avocado Verde Salsa', 'https://moribyan.com/wp-content/uploads/2024/08/IMG_0656.jpg'),
  ('Creamy Banana Milk', 'https://moribyan.com/wp-content/uploads/2024/07/IMG_0315.jpg'),
  ('Creamy Corn Salmon Chickpea Pasta', '/static/meal-images/d9da730d36fc.png'),
  ('Creamy Red Pepper Chicken Rice Bowl', '/static/meal-images/d039fe6f88f8.png'),
  ('Creamy Red Pepper Sauce', '/static/meal-images/8fb9e5aad0cd.png'),
  ('Crispy Beef Tacos', '/static/meal-images/crispy-beef-tacos-draft.png'),
  ('Cucumber Tomato Herb Salad', '/static/meal-images/f8729da4fcf6.png'),
  ('Five Bold Chicken Marinades', 'https://moribyan.com/wp-content/uploads/2025/07/IMG_0746.jpg'),
  ('Five Freezer-Ready Chicken Marinades', 'https://moribyan.com/wp-content/uploads/2026/01/IMG_8527.jpg'),
  ('Four Essential Sauces for Meal Prep', 'https://moribyan.com/wp-content/uploads/2024/02/IMG_9891.jpg'),
  ('Garlic Yogurt Sauce', '/static/meal-images/cdefb2943870.png'),
  ('Ginger Garlic Broccoli', '/static/meal-images/594470e4d4c0.png'),
  ('Greek Yogurt Chia Protein Bowl', '/static/meal-images/3844b2fedb68.png'),
  ('Homestyle Smash Burger', 'https://moribyan.com/wp-content/uploads/2023/04/93E2CC42-CD42-4D54-8EEF-F41488BD51C1.jpeg'),
  ('Kachumber Salad', '/static/meal-images/25c6d27f6b3a.png'),
  ('Kale and White Bean Salad', '/static/meal-images/e6c7d8d528fb.png'),
  ('Korean Sesame Cucumber Salad', '/static/meal-images/533968a57dda.png'),
  ('Lemon Garlic Zucchini and Mushrooms', '/static/meal-images/ee4db5c4e90f.png'),
  ('Lentil Tabbouleh', '/static/meal-images/706a9c5671be.png'),
  ('Mediterranean Cucumber Tomato Salad', '/static/meal-images/980c23861be2.png'),
  ('Mixed Green Salad with Avocado', '/static/meal-images/4f4984674df7.png'),
  ('Pistachio Baklava Pastries', 'https://moribyan.com/wp-content/uploads/2023/03/IMG_9059.jpg'),
  ('Red Pepper Chicken', '/static/meal-images/e6f8cce35412.png'),
  ('Roasted Asparagus with Garlic', '/static/meal-images/0cd01f812b20.png'),
  ('Roasted Brussels Sprouts with Balsamic', '/static/meal-images/c3cf58340087.png'),
  ('Roasted Cauliflower with Turmeric', '/static/meal-images/c2cac428e734.png'),
  ('Roasted Sweet Potato Wedges', '/static/meal-images/257a02884c4d.png'),
  ('Sardine and Avocado Breakfast Salad', '/static/meal-images/db232f426a29.png'),
  ('Sautéed Spinach with Garlic', '/static/meal-images/1bca6cb5bbcf.png'),
  ('Seasoned Rice', '/static/meal-images/f5092ab6ae5d.png'),
  ('Shawarma Chicken', '/static/meal-images/bc7ad35fcdae.png'),
  ('Shawarma Chicken Thighs', '/static/meal-images/a278c0535f0e.png'),
  ('Skillet Chicken Fajita Rice Bowl', '/static/meal-images/30374ab88e89.png'),
  ('Slow-Simmered Beef Bone Broth', 'https://moribyan.com/wp-content/uploads/2024/10/IMG_3312.jpg'),
  ('Smoked Salmon Omelet with Avocado', '/static/meal-images/8b0d0a6eb8a7.png'),
  ('Smoky Burrito Chicken', '/static/meal-images/d88216b4d092.png'),
  ('Smoky Chicken Potato Fiesta Bowl', '/static/meal-images/2fb6d869157c.png'),
  ('Smoky Chipotle Beef Mulitas', '/static/meal-images/9c862c723c13.png'),
  ('Smoky Tomato Chicken Burrito Bowl', '/static/meal-images/73990db3f204.png'),
  ('Steak and Eggs with Chimichurri Greens', '/static/meal-images/4eb6c714ec61.png'),
  ('Steamed Broccoli with Lemon', '/static/meal-images/af7a01d1d95e.png'),
  ('Steamed Green Beans with Almonds', '/static/meal-images/070adb7eee9e.png'),
  ('Stir-Fried Bok Choy with Ginger', '/static/meal-images/2cb4f451b33b.png'),
  ('Sweet and Sour Beef Rice Noodles', '/static/meal-images/e6cf250cd16f.png'),
  ('Sweet Potato Beef Sliders', '/static/meal-images/a073f073a968.png'),
  ('Three Homemade Dressings for Meal Prep', 'https://moribyan.com/wp-content/uploads/2026/02/IMG_9890-2.jpg'),
  ('Tomato Brown Rice', '/static/meal-images/876adae77cee.png'),
  ('Tomato Cucumber Salad', '/static/meal-images/9cb54bf6dded.png'),
  ('Turkey and Spinach Egg White Skillet', '/static/meal-images/7af62ff9e27a.png'),
  ('White Rice', '/static/meal-images/d053c58f5a05.png')
) AS v(title, image_url)
WHERE r.title = v.title
  AND (r.image_url IS NULL OR r.image_url = '');

COMMIT;
