from pathlib import Path
import sys
from logging.config import fileConfig
from sqlalchemy import create_engine, inspect, pool, text
from alembic import context
from alembic.script import ScriptDirectory

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.config import get_settings
from app.db import Base, GUID

# Import ALL models so Alembic sees every table
from app.models import (  # noqa: F401
    user, meal_plan, recipe, grocery, gamification,
    saved_recipe, nutrition, local_food,
    metabolic, metabolic_profile, scanned_meal,
    recipe_embedding, notification, product_label_scan, chat_usage,
)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override sqlalchemy.url from the app settings / DATABASE_URL env var
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata
LEGACY_SCHEMA_SENTINEL_TABLES = {
    "users",
    "recipes",
    "meal_plans",
    "achievements",
}


def render_item(type_, obj, autogen_context):
    """Render GUID as sa.String(36) in autogenerated migrations."""
    if type_ == "type" and isinstance(obj, GUID):
        return "sa.String(length=36)"
    return False


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True, render_item=render_item)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    url = config.get_main_option("sqlalchemy.url")
    connectable = create_engine(url, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        _bootstrap_existing_schema(connection)
        context.configure(connection=connection, target_metadata=target_metadata, render_item=render_item)
        with context.begin_transaction():
            context.run_migrations()
        _normalize_alembic_version(connection)


def _bootstrap_existing_schema(connection) -> None:
    inspector = inspect(connection)
    table_names = set(inspector.get_table_names())
    if "alembic_version" in table_names:
        return
    if not LEGACY_SCHEMA_SENTINEL_TABLES.issubset(table_names):
        return

    script = ScriptDirectory.from_config(config)
    heads = script.get_heads()
    if not heads:
        return

    connection.execute(text("CREATE TABLE IF NOT EXISTS alembic_version (version_num VARCHAR(32) NOT NULL PRIMARY KEY)"))
    for head in heads:
        connection.execute(
            text("INSERT INTO alembic_version (version_num) VALUES (:version_num) ON CONFLICT (version_num) DO NOTHING"),
            {"version_num": head},
        )
    connection.commit()


def _normalize_alembic_version(connection) -> None:
    inspector = inspect(connection)
    if "alembic_version" not in set(inspector.get_table_names()):
        return

    script = ScriptDirectory.from_config(config)
    heads = script.get_heads()
    if len(heads) != 1:
        return

    version_rows = connection.execute(text("SELECT version_num FROM alembic_version ORDER BY version_num")).fetchall()
    current_versions = [row[0] for row in version_rows]
    if current_versions == heads:
        return

    # Some legacy databases were stamped with multiple branch heads before those
    # branches were merged. Normalize them to the single repository head after a
    # successful migration run so later deploys don't keep replaying history.
    connection.execute(text("DELETE FROM alembic_version"))
    connection.execute(
        text("INSERT INTO alembic_version (version_num) VALUES (:version_num)"),
        {"version_num": heads[0]},
    )
    connection.commit()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
